ROUNDS = 20
trainPath = "antrenare"
emptyBoardPath = "emptyBoard.jpg"
BORDER = 15
ROWS = 15
COLUMNS = 15
# TEST_PATH = "evaluare/fake_test"
TEST_PATH = "antrenare"
# TEST_PATH = "custom"
# TEST_PATH = "custom_test_input"
# TEST_PATH = "custom_test_input_1"
SAVE = False